package lab7p2_víctorromero;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Google extends javax.swing.JFrame {

    static Random random = new Random();

    public Google() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();

        ab = new administrarBarra(jProgressBar1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddArchivos = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ArchivoName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ArchivoTamaño = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        AddCarpeta = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CarpetaName1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jM_Destacados = new javax.swing.JMenuItem();
        jM_Papelera = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Destacado = new javax.swing.JButton();
        Papelera = new javax.swing.JButton();
        MiUnidad = new javax.swing.JButton();
        NewCarpeta = new javax.swing.JButton();
        NewArchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(660, 449));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Archivos");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 29, 457, 82));
        jPanel3.add(ArchivoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 550, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 104, 33));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Extension");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 104, 33));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tamaño");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 104, 33));

        ArchivoTamaño.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel3.add(ArchivoTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 550, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".mp4", ".pdf", ".docx", ".mp3", ".pptx" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 550, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("ADD ARCHIVO");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 300, 60));

        AddArchivos.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(660, 449));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Add Carpetas");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 29, 457, 82));
        jPanel4.add(CarpetaName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 550, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 104, 33));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("ADD CARPETA");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 300, 60));

        javax.swing.GroupLayout AddCarpetaLayout = new javax.swing.GroupLayout(AddCarpeta.getContentPane());
        AddCarpeta.getContentPane().setLayout(AddCarpetaLayout);
        AddCarpetaLayout.setHorizontalGroup(
            AddCarpetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(AddCarpetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddCarpetaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        AddCarpetaLayout.setVerticalGroup(
            AddCarpetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
            .addGroup(AddCarpetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AddCarpetaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jM_Destacados.setText("Mover a Destacados");
        jM_Destacados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_DestacadosMouseClicked(evt);
            }
        });
        jM_Destacados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_DestacadosActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jM_Destacados);

        jM_Papelera.setText("jMenuItem2");
        jPopupMenu1.add(jM_Papelera);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Destacado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Destacado.setText("Destacados");
        jPanel2.add(Destacado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 60));

        Papelera.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Papelera.setText("Papelera");
        jPanel2.add(Papelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 170, 60));

        MiUnidad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MiUnidad.setText("Mi Unidad");
        MiUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiUnidadActionPerformed(evt);
            }
        });
        jPanel2.add(MiUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, 60));

        NewCarpeta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NewCarpeta.setText("NEW CARPETA");
        NewCarpeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewCarpetaMouseClicked(evt);
            }
        });
        jPanel2.add(NewCarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, 80));

        NewArchivo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NewArchivo.setText("NEW ARCHIVO");
        NewArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewArchivoMouseClicked(evt);
            }
        });
        jPanel2.add(NewArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Google2.png"))); // NOI18N

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton3.setText("Descargar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewArchivoMouseClicked
        this.setVisible(false);

        AddArchivos.pack();
        AddArchivos.setLocationRelativeTo(null);
        AddArchivos.setVisible(true);

    }//GEN-LAST:event_NewArchivoMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String Link = "dive.google.com/" + generateRandomLink(15);
        Archivos a = new Archivos(
                ArchivoName.getText(),
                Link,
                jComboBox1.getSelectedItem().toString(),
                Double.parseDouble(ArchivoTamaño.getText()));

        Archivos.add(a);

        AdminArchivos ap = new AdminArchivos("./archivos.virn");
        ap.cargarArchivo();
        ap.setArchivo(a);
        ap.escribirArchivo();

        JOptionPane.showMessageDialog(null, "Agregado Exitosamente!");
        ArchivoName.setText("");
        ArchivoTamaño.setText("");
        System.out.println(Archivos);

        AddArchivos.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String Link = "dive.google.com/" + generateRandomLink(5);

        Carpetas c = new Carpetas(CarpetaName1.getText(),
                Link);

        Carpetas.add(c);

        AdminCarpeta ac = new AdminCarpeta("./carpetas.virn");
        ac.cargarArchivo();
        ac.setCarpeta(c);
        ac.escribirArchivo();

        JOptionPane.showMessageDialog(null, "Agregado Exitosamente!");
        ArchivoName.setText("");
        ArchivoTamaño.setText("");
        System.out.println(Archivos);

        AddCarpeta.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void NewCarpetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewCarpetaMouseClicked
        this.setVisible(false);

        AddArchivos.pack();
        AddArchivos.setLocationRelativeTo(null);
        AddArchivos.setVisible(true);
    }//GEN-LAST:event_NewCarpetaMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        try {
            ab.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ya cargo pero no lo viste\n"
                    + "Muy lento JAJAJAJA");
        }

    }//GEN-LAST:event_jButton3MouseClicked

    private void MiUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiUnidadActionPerformed
        AdminArchivos AA = new AdminArchivos("./archivos.virn");
        AA.cargarArchivo();
        jList1.setModel(llenarJList(AA));

    }//GEN-LAST:event_MiUnidadActionPerformed

    private void jM_DestacadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_DestacadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_DestacadosActionPerformed

    private void jM_DestacadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_DestacadosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_DestacadosMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        try {
            if (evt.isMetaDown()) {
                jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Google.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Google.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Google.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Google.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Google().setVisible(true);
            }
        });
    }

    public static String generateRandomLink(int cant) {
        String caracteres = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        Random random = new Random();
        StringBuilder sb = new StringBuilder(cant);

        for (int i = 0; i < cant; i++) {
            int numRandom = random.nextInt(caracteres.length());
            char caracterRandom = caracteres.charAt(numRandom);
            sb.append(caracterRandom);
        }

        return sb.toString();
    }

    public DefaultListModel llenarJList(AdminArchivos AA) {
        DefaultListModel dlm = new DefaultListModel();

        for (Archivos a : AA.getListaArchivos()) {
            dlm.addElement(a.toString());
        }
        return dlm;
    }

    ArrayList Archivos = new ArrayList();
    ArrayList Carpetas = new ArrayList();
    administrarBarra ab;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AddArchivos;
    private javax.swing.JFrame AddCarpeta;
    private javax.swing.JTextField ArchivoName;
    private javax.swing.JFormattedTextField ArchivoTamaño;
    private javax.swing.JTextField CarpetaName1;
    private javax.swing.JButton Destacado;
    private javax.swing.JButton MiUnidad;
    private javax.swing.JButton NewArchivo;
    private javax.swing.JButton NewCarpeta;
    private javax.swing.JButton Papelera;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jM_Destacados;
    private javax.swing.JMenuItem jM_Papelera;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
